In [5]:
import pandas as pd
import numpy as np
import array as arr

In [3]:
df=pd.read_csv("C:/Users/mca/Documents/sample_week8.csv")

In [4]:
df

Rainfall  Runoff
0        105      42
1        115      46
2        103      26
3         94      39
4         95      29
5        104      33
6        120      48
7        121      58
8        127      45
9         79      20
10       133      54
11       111      37
12       127      39
13       108      34
14        85      25

In [7]:
org=np.array(df)

In [10]:
mean=np.mean(org,axis=0)
mean

array([108.46666667,  38.33333333])

In [12]:
mean_data=org-mean
mean_data

array([[ -3.46666667,   3.66666667],
       [  6.53333333,   7.66666667],
       [ -5.46666667, -12.33333333],
       [-14.46666667,   0.66666667],
       [-13.46666667,  -9.33333333],
       [ -4.46666667,  -5.33333333],
       [ 11.53333333,   9.66666667],
       [ 12.53333333,  19.66666667],
       [ 18.53333333,   6.66666667],
       [-29.46666667, -18.33333333],
       [ 24.53333333,  15.66666667],
       [  2.53333333,  -1.33333333],
       [ 18.53333333,   0.66666667],
       [ -0.46666667,  -4.33333333],
       [-23.46666667, -13.33333333]])

In [40]:
cov=np.cov(mean_data.T)
cov

array([[249.98095238, 141.04761905],
       [141.04761905, 117.52380952]])

In [19]:
len(mean_data)

15

In [41]:
x=org[:,0]
x

array([105, 115, 103,  94,  95, 104, 120, 121, 127,  79, 133, 111, 127,
       108,  85], dtype=int64)

In [42]:
y=org[:,1]
y

array([42, 46, 26, 39, 29, 33, 48, 58, 45, 20, 54, 37, 39, 34, 25],
      dtype=int64)

In [52]:
x

array([105, 115, 103,  94,  95, 104, 120, 121, 127,  79, 133, 111, 127,
       108,  85], dtype=int64)

In [55]:
np.cov(x,y)

array([[249.98095238, 141.04761905],
       [141.04761905, 117.52380952]])

In [44]:
eig_val,eig_vec=np.linalg.eig(cov)
print("Eigen vectors ",eig_vec)
print("\nEigen values ",eig_val)

Eigen vectors  [[ 0.84410476 -0.53617828]
 [ 0.53617828  0.84410476]]

Eigen values  [339.5748906   27.92987131]


In [56]:
eig_sum=sum(eig_val)
eig_sum

367.5047619047618